import {createApp} from 'vue';
import App from './App.vue';
import router from './router';
import 'node_modules/bootstrap/dist/css/bootstrap.min.css';
import 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js';
import NavBar from './components/NavBar.vue';
const app = createApp(App);
app.use(router);
app.mount('#app');
app.component('NavBar', NavBar);
